//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebAPIDemo
{
    using System;
    using System.Collections.Generic;
    
    public partial class mark
    {
        public int mark_id { get; set; }
        public Nullable<int> student_id { get; set; }
        public string subject { get; set; }
        public Nullable<int> marks { get; set; }
    
        public virtual student student { get; set; }
    }
}
